-- MySQL Script generated by MySQL Workbench
-- Fri Dec  2 00:12:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema libweb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema libweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `libweb` DEFAULT CHARACTER SET utf8 ;
USE `libweb` ;

-- -----------------------------------------------------
-- Table `libweb`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb`.`author` (
  `id_author` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_author`),
  UNIQUE INDEX `id_author_UNIQUE` (`id_author` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `libweb`.`publishing_house`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb`.`publishing_house` (
  `id_publishing_house` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_publishing_house`),
  UNIQUE INDEX `id_publishing_house_UNIQUE` (`id_publishing_house` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `libweb`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb`.`section` (
  `id_section` INT NOT NULL AUTO_INCREMENT,
  `section` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_section`),
  UNIQUE INDEX `id_section_UNIQUE` (`id_section` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `libweb`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb`.`book` (
  `id_book` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `section` INT NULL,
  `publishin_house` INT NULL,
  `year_of_publication` INT NULL,
  PRIMARY KEY (`id_book`),
  UNIQUE INDEX `id_book_UNIQUE` (`id_book` ASC) VISIBLE,
  INDEX `section_id_idx` (`section` ASC) VISIBLE,
  INDEX `publishing_house_id_idx` (`publishin_house` ASC) VISIBLE,
  CONSTRAINT `publishing_house_id`
    FOREIGN KEY (`publishin_house`)
    REFERENCES `libweb`.`publishing_house` (`id_publishing_house`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `section_id`
    FOREIGN KEY (`section`)
    REFERENCES `libweb`.`section` (`id_section`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `libweb`.`author_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb`.`author_book` (
  `id_author_book` INT NOT NULL AUTO_INCREMENT,
  `id_author` INT NOT NULL,
  `id_book` INT NOT NULL,
  PRIMARY KEY (`id_author_book`),
  UNIQUE INDEX `id_author_book_UNIQUE` (`id_author_book` ASC) VISIBLE,
  INDEX `author_id_idx` (`id_author` ASC) VISIBLE,
  INDEX `book_id_idx` (`id_book` ASC) VISIBLE,
  CONSTRAINT `author_id`
    FOREIGN KEY (`id_author`)
    REFERENCES `libweb`.`author` (`id_author`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `book_id`
    FOREIGN KEY (`id_book`)
    REFERENCES `libweb`.`book` (`id_book`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `libweb`.`metro_station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb`.`metro_station` (
  `id_metro_station` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_metro_station`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `libweb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NULL,
  `middle_name` VARCHAR(45) NULL,
  `login` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `email_status` TINYINT NULL,
  `password` VARCHAR(45) NOT NULL,
  `number_of_books` INT NULL,
  `number_of_books_taken` INT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `libweb`.`book_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb`.`book_user` (
  `id_book_user` INT NOT NULL AUTO_INCREMENT,
  `id_book` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_metro_station` INT NOT NULL,
  `there_is` TINYINT NULL,
  `prise_of_loss` DECIMAL(5,0) NULL,
  PRIMARY KEY (`id_book_user`),
  INDEX `book_id_idx` (`id_book` ASC) VISIBLE,
  INDEX `metro_station_id_idx` (`id_metro_station` ASC) VISIBLE,
  INDEX `user_id_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `book1_id`
    FOREIGN KEY (`id_book`)
    REFERENCES `libweb`.`book` (`id_book`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `metro_station_id`
    FOREIGN KEY (`id_metro_station`)
    REFERENCES `libweb`.`metro_station` (`id_metro_station`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user1_id`
    FOREIGN KEY (`id_user`)
    REFERENCES `libweb`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `libweb`.`extradition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb`.`extradition` (
  `id_extradition` INT NOT NULL AUTO_INCREMENT,
  `id_book_user` INT NOT NULL,
  `id_user` INT NOT NULL,
  `date_of_extradition` DATE NULL,
  `required_return_date` DATE NULL,
  `return_date` DATE NULL,
  `expired_on` INT NULL,
  PRIMARY KEY (`id_extradition`),
  INDEX `book_user_id_idx` (`id_book_user` ASC) VISIBLE,
  INDEX `user_id_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `book_user_id`
    FOREIGN KEY (`id_book_user`)
    REFERENCES `libweb`.`book_user` (`id_book_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`id_user`)
    REFERENCES `libweb`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
